const Actions = {
    ADD_COUNTER: 'ADD_COUNTER',
    REMOVE_COUNTER: 'REMOVE_COUNTER',
    INCREMENT_COUNTER: 'INCREMENT_COUNTER',
    DECREMENT_COUNTER: 'DECREMENT_COUNTER'
}

export default Actions;
